_extends: .github

repository:
  name: emmeowzing.github.io
  description: Blog
  homepage: https://blog.aperiodicity.com

  # A comma-separated list of topics to set on the repository
  topics: blog
  private: false