title: Tiger Lily Plants LLC.
email:
author: Emma Doyle
description: |+
  News and updates from our curated plant collections and online store.
baseurl: ""
url: https://tiger-lily-plants.com
# bluesky_username: emmeowzing
# github_username:  emmeowzing
# linkedin_username: emmeowzing
# social_links:
#   - platform: etsy
#     user_url: https://www.etsy.com/shop/TigerLilyPlants
source: src/
permalink: pretty
show_excerpts: true

paginate: 3
paginate_path: /posts/page:num/
google_analytics: G-SCV21971PF

utterances:
  repo: tigerlilyplants/tigerlilyplants.github.io
  issue_term: pathname
  label: Comment

sass:
  style: expanded
  sass_dir: _sass/
  sourcemap: always
  quiet_deps: false
  verbose: false

# Build settings
theme: minima
# theme: minimal-mistakes-jekyll

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-titles-from-headings
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-relative-links
  - jekyll-redirect-from
  - jekyll-coffeescript
  - jekyll-toc

# https://github.com/benbalter/jekyll-relative-links
relative_links:
  enabled:     true
  collections: true

exclude:
  - README.md
  - Gemfile.lock
  - Gemfile
  - LICENSE
  - CNAME

whitelist:
  - jekyll-redirect-from
