title: Observation [b]log
email: emma.ann.doyle@gmail.com
author: Emma Doyle
description: |+
  A place I stash my random observations of the world
baseurl: ""
url: https://blog.aperiodicity.com
bluesky_username: emmeowzing
github_username:  emmeowzing
linkedin_username: emmeowzing

paginate: 10
paginate_path: /posts/page:num/
google_analytics: G-2PVB8KPX2Z

# Build settings
theme: minima
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-titles-from-headings
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-relative-links
  - jekyll-last-modified-at
# https://github.com/benbalter/jekyll-relative-links
relative_links:
  enabled:     true
  collections: true
# https://github.com/gjtorikian/jekyll-last-modified-at
last-modified-at:
    date-format: '%d-%b-%y'
