version: 2.1

orbs:
  shellcheck: circleci/shellcheck@3.4.0

executors:
  default:
    docker:
      - image: cimg/base:stable

workflows:
  on-commit:
    jobs:
      - shellcheck/check:
          name: shellcheck [<< matrix.dir >>]
          matrix:
            parameters:
              dir:
                - scripts/
            alias: shellcheck
          exclude: SC2148
          filters:
            branches:
              ignore: master
